//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTNORTON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class faq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal faq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTNORTON.Resources.faq", typeof(faq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have one question about site creation, am I in the right place?.
        /// </summary>
        public static string Q01Dev {
            get {
                return ResourceManager.GetString("Q01Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have an ideia for an app or game or site, can you do it?.
        /// </summary>
        public static string Q02Dev {
            get {
                return ResourceManager.GetString("Q02Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why you don&apos;t make any apps for iOS or Android?.
        /// </summary>
        public static string Q03Dev {
            get {
                return ResourceManager.GetString("Q03Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t find your apps, who is allowed to download?.
        /// </summary>
        public static string Q04App {
            get {
                return ResourceManager.GetString("Q04App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like LoL or WoW or Minecraft ou any other game?.
        /// </summary>
        public static string Q05About {
            get {
                return ResourceManager.GetString("Q05About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You talk a lot about Microsoft, does it pay anything to you?.
        /// </summary>
        public static string Q06About {
            get {
                return ResourceManager.GetString("Q06About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t undertand anything you say, are you normal?.
        /// </summary>
        public static string Q07About {
            get {
                return ResourceManager.GetString("Q07About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, you love computers and TV Shows, any other things?.
        /// </summary>
        public static string Q08About {
            get {
                return ResourceManager.GetString("Q08About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t like you.
        /// </summary>
        public static string Q09About {
            get {
                return ResourceManager.GetString("Q09About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a Male escort? (This joke only makes sense in portuguese).
        /// </summary>
        public static string Q10About {
            get {
                return ResourceManager.GetString("Q10About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t find a few of your sites that should be on the web.
        /// </summary>
        public static string Q11Site {
            get {
                return ResourceManager.GetString("Q11Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t use my email @vtnorton.com.
        /// </summary>
        public static string Q12Site {
            get {
                return ResourceManager.GetString("Q12Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you fix my printer?.
        /// </summary>
        public static string Q13Others {
            get {
                return ResourceManager.GetString("Q13Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why doesn&apos;t have any cats photos here?.
        /// </summary>
        public static string Q14Others {
            get {
                return ResourceManager.GetString("Q14Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, get in touch for more information. .
        /// </summary>
        public static string R01 {
            get {
                return ResourceManager.GetString("R01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideias are always welcome and none are deleted. Send me your ideia, and who knows your idea comes to live. If you want an exclusive app for your company or anything like that, get in touch for a budget. If you are a Patreon, go to the exclusive Facebook Group and send me your idea there, it will have more chances to be bringed to live..
        /// </summary>
        public static string R02 {
            get {
                return ResourceManager.GetString("R02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am only one. To create apps for iOS and Android it needs a few more things that I know. And, talking about Android, I don&apos;t want to develop for a platform that I don&apos;t think is ideal. But, who knows, in a near future, I change my mind....
        /// </summary>
        public static string R03 {
            get {
                return ResourceManager.GetString("R03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The apps are being made for brazilian folks on Windows 10 (Mobile and PC). But this isn&apos;t a rule, I&apos;m currently working to bring the apps for others regions and platforms. Please, check if your region is disponible..
        /// </summary>
        public static string R04 {
            get {
                return ResourceManager.GetString("R04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I don&apos;t play. .
        /// </summary>
        public static string R05 {
            get {
                return ResourceManager.GetString("R05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh yes, I talk a lot about Microsoft and I love it. Microsoft doesn&apos;t pay me anything. Today my apps and website uses Azure services, by BizSpark from Microsoft, to be available. So, thinking a little bit more, they actually pay something for me. And yes, they paid on trip to Redmond, WA in April/2015..
        /// </summary>
        public static string R06 {
            get {
                return ResourceManager.GetString("R06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I&apos;m not normal. Mostly of the things I write is about tecnologie and TV Shows, and only people who is aware of this world will understand. Sorry. .
        /// </summary>
        public static string R07 {
            get {
                return ResourceManager.GetString("R07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love history and music..
        /// </summary>
        public static string R08 {
            get {
                return ResourceManager.GetString("R08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This isn&apos;t a question..
        /// </summary>
        public static string R09 {
            get {
                return ResourceManager.GetString("R09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That depends. (as I said this joke only work in portuguese)..
        /// </summary>
        public static string R10 {
            get {
                return ResourceManager.GetString("R10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a lot of internal changes I removed a lot of websites with the name vtnorton. If you are trying to go to icesperafeliz.vtnorton.com, go to the address &lt;a href=&quot;http://icesperafeliz.blogspot.com&quot;&gt;icesperafeliz.blogspot.com &lt;/a&gt;. The follow sites is not avalible anymore: beta.vtnorton.com, vitor.vtnorton.com, hidra.vtnorton.com, www2.vtnorton.com and hot.vtnorton.com. Projects like Jade is also shut down..
        /// </summary>
        public static string R11 {
            get {
                return ResourceManager.GetString("R11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lot of emails was deactivated, with the knowledge of the owner. There was made backups of the data and you have 90 days, after the desactivation, to ask to recive this datas. Please get in touch in &lt;a href=&quot;#contato&quot; title=&quot;Get in touch&quot; target=&quot;_blank&quot;&gt;contact section&lt;/a&gt;, after 90 days, this datas will be deleted..
        /// </summary>
        public static string R12 {
            get {
                return ResourceManager.GetString("R12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string R13 {
            get {
                return ResourceManager.GetString("R13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh yeah, there is... take a look!.
        /// </summary>
        public static string R14 {
            get {
                return ResourceManager.GetString("R14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }
    }
}
