//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTNORTON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTNORTON.Resources.index", typeof(index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look the apps.
        /// </summary>
        public static string slideOneButton {
            get {
                return ResourceManager.GetString("slideOneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still complaining that there isn&apos;t apps on Windows Store, but haven&apos;t download mine yer..
        /// </summary>
        public static string slideOneDescription {
            get {
                return ResourceManager.GetString("slideOneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 free apps.
        /// </summary>
        public static string slideOneTitle {
            get {
                return ResourceManager.GetString("slideOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;about &lt;span class=&quot;color&quot;&gt;me&lt;/span&gt;&lt;/h2&gt;.
        /// </summary>
        public static string srtAboutMe {
            get {
                return ResourceManager.GetString("srtAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All posts.
        /// </summary>
        public static string srtAllPosts {
            get {
                return ResourceManager.GetString("srtAllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft MVP, app and web developer in Microsoft world, such as C#, Asp/.Net, SQL Server and Azure. If you want to know more about me, after reading my bio, you can check my social accounts. .
        /// </summary>
        public static string srtBio {
            get {
                return ResourceManager.GetString("srtBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get to know me better.
        /// </summary>
        public static string srtBioButton {
            get {
                return ResourceManager.GetString("srtBioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not despite of being one of my specialties, the design has always being one of the biggest thing on my priority. Since making some logos to build some sites and apps..
        /// </summary>
        public static string srtDesign {
            get {
                return ResourceManager.GetString("srtDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some quick questions and answers that you most likely asked me or will ask me or you didn&apos;t ask me only because you don&apos;t know me yet. .
        /// </summary>
        public static string srtFAQDescription {
            get {
                return ResourceManager.GetString("srtFAQDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string srtFAQTitle {
            get {
                return ResourceManager.GetString("srtFAQTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design por Themefisher Team (adaptado). Copyright © 2015. Vítor Norton - Mudando o mundo um bit de cada vez..
        /// </summary>
        public static string srtFooterMessage {
            get {
                return ResourceManager.GetString("srtFooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of code.
        /// </summary>
        public static string srtLinesOfCode {
            get {
                return ResourceManager.GetString("srtLinesOfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already lost the count of how many apps I released, in 2015 it was 5. So, I&apos;m kinda good at it. If wasn&apos;t for that I won&apos;t have more than 10K downloads. .
        /// </summary>
        public static string srtMobile {
            get {
                return ResourceManager.GetString("srtMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positeve feedback.
        /// </summary>
        public static string srtPositiveFeedback {
            get {
                return ResourceManager.GetString("srtPositiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published applications.
        /// </summary>
        public static string srtPublishedApps {
            get {
                return ResourceManager.GetString("srtPublishedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string srtReadMore {
            get {
                return ResourceManager.GetString("srtReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;my &lt;span class=&quot;color&quot;&gt;skills&lt;/span&gt;&lt;/h2&gt;.
        /// </summary>
        public static string srtSkills {
            get {
                return ResourceManager.GetString("srtSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project.
        /// </summary>
        public static string srtTheProject {
            get {
                return ResourceManager.GetString("srtTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the project.
        /// </summary>
        public static string srtTheProjectButton {
            get {
                return ResourceManager.GetString("srtTheProjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Do something amazing&quot;, this is my mantra. And because of that I&apos;m working to realease a few awesome apps, and you have the chance to see how I got here. Read below.
        /// </summary>
        public static string srtTheProjectDescription {
            get {
                return ResourceManager.GetString("srtTheProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I make stuffs in web for living. And that is for a long, long time. I have a big knowledge in Asp/.Net, HTML5, CSS3 and JavaScript. .
        /// </summary>
        public static string srtWeb {
            get {
                return ResourceManager.GetString("srtWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today I am a Microsoft MVP in Windows experience, since I like to help a lot of people on web and because I&apos;m, with proud, an Windows Insider..
        /// </summary>
        public static string srtWindows {
            get {
                return ResourceManager.GetString("srtWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View app.
        /// </summary>
        public static string ViewApp {
            get {
                return ResourceManager.GetString("ViewApp", resourceCulture);
            }
        }
    }
}
