//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTNORTON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class master {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal master() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTNORTON.Resources.master", typeof(master).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fun.
        /// </summary>
        public static string Fun {
            get {
                return ResourceManager.GetString("Fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;my &lt;span class=&quot;color&quot;&gt;apps&lt;/span&gt;&lt;/h2&gt;.
        /// </summary>
        public static string MyApps {
            get {
                return ResourceManager.GetString("MyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outros.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string srtAbout {
            get {
                return ResourceManager.GetString("srtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string srtCategory {
            get {
                return ResourceManager.GetString("srtCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string srtContact {
            get {
                return ResourceManager.GetString("srtContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;ideas, &lt;span class=&quot;color&quot;&gt;suggestions&lt;/span&gt; or a simple chat&lt;/h2&gt;.
        /// </summary>
        public static string srtContact1 {
            get {
                return ResourceManager.GetString("srtContact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m open to listen you ideas, suggestions and even a simple chat, and in case you want to send some information about the abusive use of any inapropriate text, image, or other kinds of things, please use the form in this page or the email below. &lt;br/&gt;Besides your name, e-mail and message, I&apos;m not reciving anythig about you. Absolute none. Zero. .
        /// </summary>
        public static string srtContactText {
            get {
                return ResourceManager.GetString("srtContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of contact.
        /// </summary>
        public static string srtContactTile {
            get {
                return ResourceManager.GetString("srtContactTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have a few apps published on the Store, here is the place that you can find everything about it and about me.
        /// </summary>
        public static string srtDescription {
            get {
                return ResourceManager.GetString("srtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when try to send you message. I&apos;m so sorry about that. Is already going to be fixed..
        /// </summary>
        public static string srtFailToSend {
            get {
                return ResourceManager.GetString("srtFailToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design by &lt;a href=&apos;http://www.themefisher.com&apos;&gt;Themefisher Team&lt;/a&gt; (I changed it a little bit). Copyright ©. &lt;span class=&apos;color&apos;&gt;Vítor Norton&lt;/span&gt; - Changing the world one bit at time..
        /// </summary>
        public static string srtFooter {
            get {
                return ResourceManager.GetString("srtFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string srtHome {
            get {
                return ResourceManager.GetString("srtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;latest &lt;span class=&quot;color&quot;&gt;posts&lt;/span&gt;&lt;/h2&gt;.
        /// </summary>
        public static string srtLastPosts {
            get {
                return ResourceManager.GetString("srtLastPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string srtPop {
            get {
                return ResourceManager.GetString("srtPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string srtRecent {
            get {
                return ResourceManager.GetString("srtRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string srtSearch {
            get {
                return ResourceManager.GetString("srtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string srtSend {
            get {
                return ResourceManager.GetString("srtSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for getting in touch.
        /// </summary>
        public static string srtThanks {
            get {
                return ResourceManager.GetString("srtThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítor Norton | App and web developer.
        /// </summary>
        public static string srtTitle {
            get {
                return ResourceManager.GetString("srtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core&apos;s version: .
        /// </summary>
        public static string srtVersionCore {
            get {
                return ResourceManager.GetString("srtVersionCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site&apos;s version: .
        /// </summary>
        public static string srtVersionSite {
            get {
                return ResourceManager.GetString("srtVersionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail.
        /// </summary>
        public static string srtYouEmail {
            get {
                return ResourceManager.GetString("srtYouEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your menssage.
        /// </summary>
        public static string srtYouMenssage {
            get {
                return ResourceManager.GetString("srtYouMenssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string srtYouName {
            get {
                return ResourceManager.GetString("srtYouName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
