//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTNORTON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class qrcodebc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qrcodebc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTNORTON.Resources.qrcodebc", typeof(qrcodebc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscrive to my calendar and be aware of every event, release, update or any thing. .
        /// </summary>
        public static string CalendarDescription {
            get {
                return ResourceManager.GetString("CalendarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string CalendarioTitle {
            get {
                return ResourceManager.GetString("CalendarioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call me for one talk.
        /// </summary>
        public static string CallForTalk {
            get {
                return ResourceManager.GetString("CallForTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and add me in your contact list. Here is my contact profile for you!.
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;span class=&quot;color&quot;&gt;private&lt;/span&gt; web site&lt;/h2&gt;.
        /// </summary>
        public static string ExclusiveSite {
            get {
                return ResourceManager.GetString("ExclusiveSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need my logo, or logo of any of my apps, here is the place. Download then!.
        /// </summary>
        public static string MIDDescription {
            get {
                return ResourceManager.GetString("MIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press pack.
        /// </summary>
        public static string MIDTitle {
            get {
                return ResourceManager.GetString("MIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;span class=&quot;color&quot;&gt;patreon&lt;/span&gt;&lt;/h2&gt;.
        /// </summary>
        public static string Patreon {
            get {
                return ResourceManager.GetString("Patreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to main site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscrive.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;span class=&quot;color&quot;&gt;talks&lt;/span&gt;&lt;/h2&gt;.
        /// </summary>
        public static string Talks {
            get {
                return ResourceManager.GetString("Talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have made a few beautiful wallpapers, feel free to use one of then and share!.
        /// </summary>
        public static string WallpaperDescription {
            get {
                return ResourceManager.GetString("WallpaperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string WallpaperTitle {
            get {
                return ResourceManager.GetString("WallpaperTitle", resourceCulture);
            }
        }
    }
}
