//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTNORTON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class darkmode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal darkmode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTNORTON.Resources.darkmode", typeof(darkmode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute.
        /// </summary>
        public static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a totally free open source, and yes, you can help develop it! You can find the full documentation and the how-to-help-guide on the GitHub repository. &lt;/p&gt;
        ///
        ///&lt;p&gt;To help develop it you won&apos;t need much, just one GitHub client for you PC and one Notepad (but if you want to use Visual Studio Code or Formula - Universal Code Editor, I&apos;m not going to be mad)..
        /// </summary>
        public static string ContributeDetail {
            get {
                return ResourceManager.GetString("ContributeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t matter of you Windows is on dark mode or on the light mode. The websites you visit isn&apos;t, so this Microsoft Edge extension is about to change it. When enabled, this extension will put your favorite web site on the dark mode! So don&apos;t forget to put Windows and Edge on Dark Mode&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Note: This is a working in progress extension, a beta version.&lt;/strong&gt;.
        /// </summary>
        public static string ExtensionDetail {
            get {
                return ResourceManager.GetString("ExtensionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the GitHub repository.
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This extension isn&apos;t available at the Windows Store (yet), but I&apos;m working on this, so you may consider this as a beta! &lt;/p&gt;
        ///
        ///&lt;p&gt;To install this extension you have to enable the &quot;Dev Mode&quot; of Microsoft Edge, to do that, go to about:flags and select &quot;Enable extension developer features&quot;, with this enable, go to the three dot menu and select Extension. Click on the Load Extension button and select the folder you saved the download. &lt;/p&gt;
        ///
        ///&lt;p&gt;Please, note that, you will not be alerted if a new version come  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InstallDetail {
            get {
                return ResourceManager.GetString("InstallDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download it now.
        /// </summary>
        public static string Link1 {
            get {
                return ResourceManager.GetString("Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get involved.
        /// </summary>
        public static string Link2 {
            get {
                return ResourceManager.GetString("Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string Link3 {
            get {
                return ResourceManager.GetString("Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        public static string Link4 {
            get {
                return ResourceManager.GetString("Link4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t matter of you Windows is on dark mode or on the light mode. The websites you visit isn&apos;t, so this Microsoft Edge extension is about to change it..
        /// </summary>
        public static string ThisAppDescription {
            get {
                return ResourceManager.GetString("ThisAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s put everything on the dark mode.
        /// </summary>
        public static string ToDarkMode {
            get {
                return ResourceManager.GetString("ToDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putting every website on the internet on the dark mode is kinda of impossible, but this doesn&apos;t mean that I won&apos;t try. This is just a beta version so only a few websites are available, but if you want to help add more websites the source code is opened! And if you don&apos;t know how to code but still want to help, you can send feedback to me asking to add new sites. &lt;/p&gt;
        ///
        ///&lt;p&gt;If you find any problem, please report it!.
        /// </summary>
        public static string ToDarkModeDetail {
            get {
                return ResourceManager.GetString("ToDarkModeDetail", resourceCulture);
            }
        }
    }
}
