//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTNORTON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class formula {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal formula() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTNORTON.Resources.formula", typeof(formula).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize your files in tabs and work with more than one file at time, just like you are used to.&lt;/p&gt;
        ///
        ///&lt;p&gt;And there is something else: you can use the shortcuts as you already know to save, open and to make a new file.&lt;/p&gt;
        ///
        ///&lt;p&gt;Have fun codding, just like I had writing this app! ;) Don&apos;t forget you coffee!.
        /// </summary>
        public static string FeaturesContent {
            get {
                return ResourceManager.GetString("FeaturesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can write and read all languages, but you experience will be better with: C#, C, C++, CSS, HTML, Java, JavaScript, JSON, LUA, Pascal, PHP, Phyton, SQL, XML and more.&lt;/p&gt;
        ///
        ///&lt;p&gt;Also you can create new files with this simple code editor, isn&apos;t this awesome?!.
        /// </summary>
        public static string LanguagesContent {
            get {
                return ResourceManager.GetString("LanguagesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The must complete editor at the Windows Mobile store.&quot; - Biel.
        /// </summary>
        public static string Review1 {
            get {
                return ResourceManager.GetString("Review1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This app is perfect for operations on javascript code since I&apos;ve used it for that. It is fresh small fast and non-bloated.&quot; - Fedja.
        /// </summary>
        public static string Review2 {
            get {
                return ResourceManager.GetString("Review2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Better looking and significantly more functional than any other windows mobile code editor... And it&apos;s UWP!&quot; - Tom.
        /// </summary>
        public static string Review3 {
            get {
                return ResourceManager.GetString("Review3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;When I&apos;m not behind a pc I&apos;m using this app to write a few lines of code :-)&quot; - Cynthia.
        /// </summary>
        public static string Review4 {
            get {
                return ResourceManager.GetString("Review4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;span class=&quot;notranslate&quot;&gt;Formula&lt;/span&gt;.
        /// </summary>
        public static string TheFormula {
            get {
                return ResourceManager.GetString("TheFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many times do you get out of your office and remember a line of code that can fix the biggest bug you have? Guest what, you will forgot that line of code, you simply have to write it right out way. It can&apos;t wait you to get to the office. That&apos;s why Formula - Universal Code Editor is here.&lt;/p&gt;
        ///
        ///&lt;p&gt;You can use Formula on you phone, tablet and desktop. Also I am working to make this app great for the Continuum..
        /// </summary>
        public static string TheFormulaContent {
            get {
                return ResourceManager.GetString("TheFormulaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many times do you get out of your office and remember a line of code that can fix the biggest bug you have? Formula is here for you!.
        /// </summary>
        public static string ThisAppDescription {
            get {
                return ResourceManager.GetString("ThisAppDescription", resourceCulture);
            }
        }
    }
}
