//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTNORTON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class terre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal terre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTNORTON.Resources.terre", typeof(terre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining regular and irregular verbs of our Portuguese language in all tenses.
        /// </summary>
        public static string DouaiDescription {
            get {
                return ResourceManager.GetString("DouaiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I had learned a lot with this app&quot; - Marcelo.
        /// </summary>
        public static string DouaiReview1 {
            get {
                return ResourceManager.GetString("DouaiReview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The best app for me&quot; - Jean.
        /// </summary>
        public static string DouaiReview11 {
            get {
                return ResourceManager.GetString("DouaiReview11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this: Present, Imperfect, Perfect Present, more-than-perfect past, future, future of this, the present conditional, imperfect subjunctive tense, future subjunctive, imperative , infinitive and gerund..
        /// </summary>
        public static string DouaiSecondDescription {
            get {
                return ResourceManager.GetString("DouaiSecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjugations.
        /// </summary>
        public static string DouaiSecondTitle {
            get {
                return ResourceManager.GetString("DouaiSecondTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining regular and irregular verbs of our Portuguese language in all tenses.
        /// </summary>
        public static string DouaiShortDescription {
            get {
                return ResourceManager.GetString("DouaiShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate and converts easily minutes, turning in hours, days, or even years or seconds. Perfect app for those who like to do marathons series and need to know how many episodes you can watch up to your next appointment, or you going to the movies and you want to eat something later, but can not miss the bus schedule. Do not waste time counting!.
        /// </summary>
        public static string LyonDescription {
            get {
                return ResourceManager.GetString("LyonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate and converts easily minutes, turning in hours, days, or even years or seconds..
        /// </summary>
        public static string LyonShortDescription3 {
            get {
                return ResourceManager.GetString("LyonShortDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isn&apos;t rare occasions where we need to give away someone with this application is easy. Just add the track numbers to be drawn and it will do the work for you. Try it.
        ///
        ///Now it can do decimal numbers!.
        /// </summary>
        public static string NiceDescription {
            get {
                return ResourceManager.GetString("NiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isn&apos;t rare occasions where we need to give away someone with this application is easy..
        /// </summary>
        public static string NiceShortDescription {
            get {
                return ResourceManager.GetString("NiceShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A game can destroy as well as to strengthen friendships. Take stronger drink, or that is closer to you, and will play the famous &apos;Never ever&apos; , where every time you&apos;ve done something that it is showed on the screen you should drink. The rule is simple, the game is known, then what are you waiting? Call your closest friends for a round of &apos;Never ever&apos;. 
        ///
        ///It is more than 600 sentences (in Portuguese for now).
        /// </summary>
        public static string PasadenaDescription {
            get {
                return ResourceManager.GetString("PasadenaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take stronger drink, or that is closer to you, and will play the famous &apos;Never ever&apos; , where every time you&apos;ve done something that it is showed on the screen you should drink. .
        /// </summary>
        public static string PasadenaShortDescription {
            get {
                return ResourceManager.GetString("PasadenaShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can know, even on the phone, where the Olympic Torch will be on Brazil. Check the list of the cities.
        /// </summary>
        public static string RioDescription {
            get {
                return ResourceManager.GetString("RioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can know, even on the phone, where the Olympic Torch will be on Brazil. Check the list of the cities.
        /// </summary>
        public static string RioShortDescription4 {
            get {
                return ResourceManager.GetString("RioShortDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TerreDescription {
            get {
                return ResourceManager.GetString("TerreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those who never played such a game like this or have never heard that throw the first stone! The best game of truth and consequence that the Windows Store has seen so far, has several bottles according to the occasion (in family, in the square, between friends, drunk, with the bests , alone,in the classroom and among couples) , with questions and pre-defined challenges is fun in the right esste application!.
        /// </summary>
        public static string VegasDescription {
            get {
                return ResourceManager.GetString("VegasDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best game of truth and consequence that the Windows Store has seen so far, has several bottles according to the occasion..
        /// </summary>
        public static string VegasShortDescription {
            get {
                return ResourceManager.GetString("VegasShortDescription", resourceCulture);
            }
        }
    }
}
