//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTNORTON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class heartthrob {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal heartthrob() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTNORTON.Resources.heartthrob", typeof(heartthrob).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All apps.
        /// </summary>
        public static string AllApps {
            get {
                return ResourceManager.GetString("AllApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a unknow error. Sorry about that, it&apos;s been handled..
        /// </summary>
        public static string erro000Description {
            get {
                return ResourceManager.GetString("erro000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong.
        /// </summary>
        public static string erro000Title {
            get {
                return ResourceManager.GetString("erro000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a public place of my website. Sorry: - (&lt;/ p&gt;
        ///&lt;p&gt; If you believe you should have access to this part of the site, please contact me.
        /// </summary>
        public static string erro403Description {
            get {
                return ResourceManager.GetString("erro403Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You shall not pass.
        /// </summary>
        public static string erro403Title {
            get {
                return ResourceManager.GetString("erro403Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the page you are looking for no longer exists. It may be temporarily unavailable, or moved from place or no longer exists. &lt;/ p&gt; &lt;p&gt; Please review the URL you entered looking for any errors and try again. Or use the search bar and look for what is missing and take a walk around the rest of the site..
        /// </summary>
        public static string erro404Description {
            get {
                return ResourceManager.GetString("erro404Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you are looking for is not here.
        /// </summary>
        public static string erro404Title {
            get {
                return ResourceManager.GetString("erro404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probably this is a server error that is already being resolved. Please try again later .. &lt;/ p&gt;
        ///&lt;p&gt; If you want to contact and report the problem use the contato@vtnorton.com email to inform me about the problem..
        /// </summary>
        public static string erro500Description {
            get {
                return ResourceManager.GetString("erro500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong.
        /// </summary>
        public static string erro500Title {
            get {
                return ResourceManager.GetString("erro500Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get inside of Windows.
        /// </summary>
        public static string erroBlog {
            get {
                return ResourceManager.GetString("erroBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read about my apps.
        /// </summary>
        public static string erroDev {
            get {
                return ResourceManager.GetString("erroDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover new events.
        /// </summary>
        public static string erroEventos {
            get {
                return ResourceManager.GetString("erroEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to code.
        /// </summary>
        public static string erroGaroto {
            get {
                return ResourceManager.GetString("erroGaroto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Changing the world one bit at time&quot;.
        /// </summary>
        public static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        public static string navAllEvents {
            get {
                return ResourceManager.GetString("navAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All posts.
        /// </summary>
        public static string navAllPosts {
            get {
                return ResourceManager.GetString("navAllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answering Feedback.
        /// </summary>
        public static string navAnswering {
            get {
                return ResourceManager.GetString("navAnswering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string navApps {
            get {
                return ResourceManager.GetString("navApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string navDesenvolvimento {
            get {
                return ResourceManager.GetString("navDesenvolvimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer notes.
        /// </summary>
        public static string navDeveloperNotes {
            get {
                return ResourceManager.GetString("navDeveloperNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string navEvents {
            get {
                return ResourceManager.GetString("navEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string navHome {
            get {
                return ResourceManager.GetString("navHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the next update.
        /// </summary>
        public static string navInTheNext {
            get {
                return ResourceManager.GetString("navInTheNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me, myself.
        /// </summary>
        public static string navMe {
            get {
                return ResourceManager.GetString("navMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string navNews {
            get {
                return ResourceManager.GetString("navNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string navOthers {
            get {
                return ResourceManager.GetString("navOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal blog.
        /// </summary>
        public static string navPersonal {
            get {
                return ResourceManager.GetString("navPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string navProjetos {
            get {
                return ResourceManager.GetString("navProjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string navTips {
            get {
                return ResourceManager.GetString("navTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates and Releases.
        /// </summary>
        public static string navUpdates {
            get {
                return ResourceManager.GetString("navUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open search box.
        /// </summary>
        public static string openSearch {
            get {
                return ResourceManager.GetString("openSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
    }
}
