//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vtnorton.Resources.Views.Shared {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout_pt_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _Layout_pt_() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vtnorton.Resources.Views.Shared._Layout.pt.", typeof(_Layout_pt_).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Todos os aplicativos.
        /// </summary>
        public static string AllApps {
            get {
                return ResourceManager.GetString("AllApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &quot;Mudando o mundo um bit de cada vez&quot;.
        /// </summary>
        public static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Todos os eventos.
        /// </summary>
        public static string navAllEvents {
            get {
                return ResourceManager.GetString("navAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Todas as postagens.
        /// </summary>
        public static string navAllPosts {
            get {
                return ResourceManager.GetString("navAllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Respondendo feedback.
        /// </summary>
        public static string navAnswering {
            get {
                return ResourceManager.GetString("navAnswering", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aplicativos.
        /// </summary>
        public static string navApps {
            get {
                return ResourceManager.GetString("navApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Desenvolvimento.
        /// </summary>
        public static string navDesenvolvimento {
            get {
                return ResourceManager.GetString("navDesenvolvimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Notas do desenvolvedor.
        /// </summary>
        public static string navDeveloperNotes {
            get {
                return ResourceManager.GetString("navDeveloperNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Eventos.
        /// </summary>
        public static string navEvents {
            get {
                return ResourceManager.GetString("navEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Início.
        /// </summary>
        public static string navHome {
            get {
                return ResourceManager.GetString("navHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Na próxima atualização.
        /// </summary>
        public static string navInTheNext {
            get {
                return ResourceManager.GetString("navInTheNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Eu, eu mesmo.
        /// </summary>
        public static string navMe {
            get {
                return ResourceManager.GetString("navMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Novidades.
        /// </summary>
        public static string navNews {
            get {
                return ResourceManager.GetString("navNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Outros.
        /// </summary>
        public static string navOthers {
            get {
                return ResourceManager.GetString("navOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Blog pessoal.
        /// </summary>
        public static string navPersonal {
            get {
                return ResourceManager.GetString("navPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Projetos.
        /// </summary>
        public static string navProjetos {
            get {
                return ResourceManager.GetString("navProjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dicas e utilizades.
        /// </summary>
        public static string navTips {
            get {
                return ResourceManager.GetString("navTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Atualizações e lançamentos.
        /// </summary>
        public static string navUpdates {
            get {
                return ResourceManager.GetString("navUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Abrir caixa de pesquisa.
        /// </summary>
        public static string openSearch {
            get {
                return ResourceManager.GetString("openSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enviar feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
    }
}
