DROP TABLE tbl_country;
CREATE TABLE tbl_country(
	Id		INT IDENTITY (1,1)	NOT NULL,
	Code	VARCHAR(2)			NOT NULL,
	Name	VARCHAR(120)		NOT NULL	
);
CREATE CLUSTERED INDEX Id ON tbl_country (Id);

INSERT INTO tbl_country (Code, Name) VALUES ('AF', 'Afghanistan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AX', 'Åland Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AL', 'Albania'); 
INSERT INTO tbl_country (Code, Name) VALUES ('DZ', 'Algeria'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AS', 'American Samoa'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AD', 'Andorra'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AO', 'Angola'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AI', 'Anguilla'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AQ', 'Antarctica'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AG', 'Antigua and Barbuda'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AR', 'Argentina'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AM', 'Armenia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AW', 'Aruba'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AC', 'Ascension Island'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AU', 'Australia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AT', 'Austria'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AZ', 'Azerbaijan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BS', 'Bahamas'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BH', 'Bahrain'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BD', 'Bangladesh'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BB', 'Barbados'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BY', 'Belarus'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BE', 'Belgium'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BZ', 'Belize'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BJ', 'Benin'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BM', 'Bermuda'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BT', 'Bhutan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BO', 'Bolivia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BQ', 'Bonaire, Sint Eustatius, and Saba'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BA', 'Bosnia and Herzegovina'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BW', 'Botswana'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BV', 'Bouvet Island'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BR', 'Brazil'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IO', 'British Indian Ocean Territory'); 
INSERT INTO tbl_country (Code, Name) VALUES ('VG', 'British Virgin Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BN', 'Brunei'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BG', 'Bulgaria'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BF', 'Burkina Faso'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BI', 'Burundi'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KH', 'Cambodia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CM', 'Cameroon'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CA', 'Canada'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IC', 'Canary Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CV', 'Cape Verde'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KY', 'Cayman Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CF', 'Central African Republic'); 
INSERT INTO tbl_country (Code, Name) VALUES ('EA', 'Ceuta and Melilla'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TD', 'Chad'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CL', 'Chile'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CN', 'China'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CX', 'Christmas Island'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CP', 'Clipperton Island'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CC', 'Cocos [Keeling] Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CO', 'Colombia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KM', 'Comoros'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CG', 'Congo - Brazzaville'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CD', 'Congo - Kinshasa'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CK', 'Cook Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CR', 'Costa Rica'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CI', 'Côte d’Ivoire'); 
INSERT INTO tbl_country (Code, Name) VALUES ('HR', 'Croatia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CU', 'Cuba'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CW', 'Curaçao'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CY', 'Cyprus'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CZ', 'Czech Republic'); 
INSERT INTO tbl_country (Code, Name) VALUES ('DK', 'Denmark'); 
INSERT INTO tbl_country (Code, Name) VALUES ('DG', 'Diego Garcia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('DJ', 'Djibouti'); 
INSERT INTO tbl_country (Code, Name) VALUES ('DM', 'Dominica'); 
INSERT INTO tbl_country (Code, Name) VALUES ('DO', 'Dominican Republic'); 
INSERT INTO tbl_country (Code, Name) VALUES ('EC', 'Ecuador'); 
INSERT INTO tbl_country (Code, Name) VALUES ('EG', 'Egypt'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SV', 'El Salvador'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GQ', 'Equatorial Guinea'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ER', 'Eritrea'); 
INSERT INTO tbl_country (Code, Name) VALUES ('EE', 'Estonia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ET', 'Ethiopia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('EU', 'European Union'); 
INSERT INTO tbl_country (Code, Name) VALUES ('FK', 'Falkland Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('FO', 'Faroe Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('FJ', 'Fiji'); 
INSERT INTO tbl_country (Code, Name) VALUES ('FI', 'Finland'); 
INSERT INTO tbl_country (Code, Name) VALUES ('FR', 'France'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GF', 'French Guiana'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PF', 'French Polynesia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TF', 'French Southern Territories'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GA', 'Gabon'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GM', 'Gambia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GE', 'Georgia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('DE', 'Germany'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GH', 'Ghana'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GI', 'Gibraltar'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GR', 'Greece'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GL', 'Greenland'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GD', 'Grenada'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GP', 'Guadeloupe'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GU', 'Guam'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GT', 'Guatemala'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GG', 'Guernsey'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GN', 'Guinea'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GW', 'Guinea-Bissau'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GY', 'Guyana'); 
INSERT INTO tbl_country (Code, Name) VALUES ('HT', 'Haiti'); 
INSERT INTO tbl_country (Code, Name) VALUES ('HM', 'Heard Island and McDonald Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('HN', 'Honduras'); 
INSERT INTO tbl_country (Code, Name) VALUES ('HK', 'Hong Kong SAR China'); 
INSERT INTO tbl_country (Code, Name) VALUES ('HU', 'Hungary'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IS', 'Iceland'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IN', 'India'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ID', 'Indonesia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IR', 'Iran'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IQ', 'Iraq'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IE', 'Ireland'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IM', 'Isle of Man'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IL', 'Israel'); 
INSERT INTO tbl_country (Code, Name) VALUES ('IT', 'Italy'); 
INSERT INTO tbl_country (Code, Name) VALUES ('JM', 'Jamaica'); 
INSERT INTO tbl_country (Code, Name) VALUES ('JP', 'Japan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('JE', 'Jersey'); 
INSERT INTO tbl_country (Code, Name) VALUES ('JO', 'Jordan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KZ', 'Kazakhstan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KE', 'Kenya'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KI', 'Kiribati'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KW', 'Kuwait'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KG', 'Kyrgyzstan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LA', 'Laos'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LV', 'Latvia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LB', 'Lebanon'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LS', 'Lesotho'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LR', 'Liberia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LY', 'Libya'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LI', 'Liechtenstein'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LT', 'Lithuania'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LU', 'Luxembourg'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MO', 'Macau SAR China'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MK', 'Macedonia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MG', 'Madagascar'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MW', 'Malawi'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MY', 'Malaysia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MV', 'Maldives'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ML', 'Mali'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MT', 'Malta'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MH', 'Marshall Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MQ', 'Martinique'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MR', 'Mauritania'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MU', 'Mauritius'); 
INSERT INTO tbl_country (Code, Name) VALUES ('YT', 'Mayotte'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MX', 'Mexico'); 
INSERT INTO tbl_country (Code, Name) VALUES ('FM', 'Micronesia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MD', 'Moldova'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MC', 'Monaco'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MN', 'Mongolia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ME', 'Montenegro'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MS', 'Montserrat'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MA', 'Morocco'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MZ', 'Mozambique'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MM', 'Myanmar [Burma]'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NA', 'Namibia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NR', 'Nauru'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NP', 'Nepal'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NL', 'Netherlands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AN', 'Netherlands Antilles'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NC', 'New Caledonia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NZ', 'New Zealand'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NI', 'Nicaragua'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NE', 'Niger'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NG', 'Nigeria'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NU', 'Niue'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NF', 'Norfolk Island'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KP', 'North Korea'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MP', 'Northern Mariana Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('NO', 'Norway'); 
INSERT INTO tbl_country (Code, Name) VALUES ('OM', 'Oman'); 
INSERT INTO tbl_country (Code, Name) VALUES ('QO', 'Outlying Oceania'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PK', 'Pakistan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PW', 'Palau'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PS', 'Palestinian Territories'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PA', 'Panama'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PG', 'Papua New Guinea'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PY', 'Paraguay'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PE', 'Peru'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PH', 'Philippines'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PN', 'Pitcairn Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PL', 'Poland'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PT', 'Portugal'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PR', 'Puerto Rico'); 
INSERT INTO tbl_country (Code, Name) VALUES ('QA', 'Qatar'); 
INSERT INTO tbl_country (Code, Name) VALUES ('RE', 'Réunion'); 
INSERT INTO tbl_country (Code, Name) VALUES ('RO', 'Romania'); 
INSERT INTO tbl_country (Code, Name) VALUES ('RU', 'Russia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('RW', 'Rwanda'); 
INSERT INTO tbl_country (Code, Name) VALUES ('BL', 'Saint Barthélemy'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SH', 'Saint Helena'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KN', 'Saint Kitts and Nevis'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LC', 'Saint Lucia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('MF', 'Saint Martin'); 
INSERT INTO tbl_country (Code, Name) VALUES ('PM', 'Saint Pierre and Miquelon'); 
INSERT INTO tbl_country (Code, Name) VALUES ('VC', 'Saint Vincent and the Grenadines'); 
INSERT INTO tbl_country (Code, Name) VALUES ('WS', 'Samoa'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SM', 'San Marino'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ST', 'São Tomé and Príncipe'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SA', 'Saudi Arabia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SN', 'Senegal'); 
INSERT INTO tbl_country (Code, Name) VALUES ('RS', 'Serbia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CS', 'Serbia and Montenegro'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SC', 'Seychelles'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SL', 'Sierra Leone'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SG', 'Singapore'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SX', 'Sint Maarten'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SK', 'Slovakia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SI', 'Slovenia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SB', 'Solomon Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SO', 'Somalia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ZA', 'South Africa'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GS', 'South Georgia and the South Sandwich Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('KR', 'South Korea'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SS', 'South Sudan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ES', 'Spain'); 
INSERT INTO tbl_country (Code, Name) VALUES ('LK', 'Sri Lanka'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SD', 'Sudan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SR', 'Suriname'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SJ', 'Svalbard and Jan Mayen'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SZ', 'Swaziland'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SE', 'Sweden'); 
INSERT INTO tbl_country (Code, Name) VALUES ('CH', 'Switzerland'); 
INSERT INTO tbl_country (Code, Name) VALUES ('SY', 'Syria'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TW', 'Taiwan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TJ', 'Tajikistan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TZ', 'Tanzania'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TH', 'Thailand'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TL', 'Timor-Leste'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TG', 'Togo'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TK', 'Tokelau'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TO', 'Tonga'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TT', 'Trinidad and Tobago'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TA', 'Tristan da Cunha'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TN', 'Tunisia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TR', 'Turkey'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TM', 'Turkmenistan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TC', 'Turks and Caicos Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('TV', 'Tuvalu'); 
INSERT INTO tbl_country (Code, Name) VALUES ('UM', 'U.S. Minor Outlying Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('VI', 'U.S. Virgin Islands'); 
INSERT INTO tbl_country (Code, Name) VALUES ('UG', 'Uganda'); 
INSERT INTO tbl_country (Code, Name) VALUES ('UA', 'Ukraine'); 
INSERT INTO tbl_country (Code, Name) VALUES ('AE', 'United Arab Emirates'); 
INSERT INTO tbl_country (Code, Name) VALUES ('GB', 'United Kingdom'); 
INSERT INTO tbl_country (Code, Name) VALUES ('US', 'United States'); 
INSERT INTO tbl_country (Code, Name) VALUES ('UY', 'Uruguay'); 
INSERT INTO tbl_country (Code, Name) VALUES ('UZ', 'Uzbekistan'); 
INSERT INTO tbl_country (Code, Name) VALUES ('VU', 'Vanuatu'); 
INSERT INTO tbl_country (Code, Name) VALUES ('VA', 'Vatican City'); 
INSERT INTO tbl_country (Code, Name) VALUES ('VE', 'Venezuela'); 
INSERT INTO tbl_country (Code, Name) VALUES ('VN', 'Vietnam'); 
INSERT INTO tbl_country (Code, Name) VALUES ('WF', 'Wallis and Futuna'); 
INSERT INTO tbl_country (Code, Name) VALUES ('EH', 'Western Sahara'); 
INSERT INTO tbl_country (Code, Name) VALUES ('YE', 'Yemen'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ZM', 'Zambia'); 
INSERT INTO tbl_country (Code, Name) VALUES ('ZW', 'Zimbabwe'); 
