DROP TABLE tbl_farm;

CREATE TABLE tbl_farm (
	Id INT IDENTITY(1, 1) NOT NULL
	,Size INT NOT NULL
	,Type INT NOT NULL
	,AllowedUsers VARCHAR(300)
	,NAME VARCHAR(50) NOT NULL
	,OWNER VARCHAR(50) NOT NULL
	,IdRegion INT NOT NULL
	,IdCountry INT NOT NULL
	,Address VARCHAR(330)
	);

CREATE CLUSTERED INDEX Id ON tbl_farm (Id); 